### ISSUE TITLE
Unables to create Opengl context! Could not create GL context

### ISSUE THREAD

**Issue by CreamChatilly** [naikari/naikari#16]
#### Naikari version
Naikari v0.9.0 (linux-x86_64)

#### Describe the bug
As the title say, the game do not launch and give me this Error: 
ERROR ../src/opengl.c:297 [gl_createWindow]: Unable to create OpenGl context! Could not create GL context
Aborted (core dumped) 

#### To Reproduce
1. Try to launch naikari
2.  Faild

#### Expected behavior
well you know, Launch the game or something like this.

#### Additional context (optional)
 It's a old laptop, but it's should be running Opengl 3.2
Arch Linux btw.  ;)

**Comment by onpon4** [comment]
That error generally means that your hardware doesn't support the correct OpenGL version. Could I see the output of this command?

```sh
glxinfo | grep version
```

🦇

**Comment by CreamChatilly** [comment]
[GreenWizard@Midorin ~]$ glxinfo | grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL version string: 2.1 Mesa 23.1.6
OpenGL shading language version string: 1.20
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 23.1.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16


yep my hardware can't support the correct OpenGL. :/

**Comment by onpon4** [comment]
Yeah, version 3.1 is required at a minimum. For Intel CPUs, it seems the oldest ones which came with integrated graphics controllers that could handle OpenGL 3.1 were the Sandy Bridge CPUs, released in 2011.

Depending on the laptop, it's plausible that you might be able to install a video card to get around this.

It could also be possible to add an OpenGL 2.1 compatibility mode to Naikari, if someone is willing to work on it. (It's not something I'm going to do, but I'd be happy to accept contributions to that end.)

🦇

**Comment by CreamChatilly** [comment]
Yeah I tried:
`LIBGL_ALWAYS_SOFTWARE=true ./naikari-0.9.0.AppImage`
But bash can't find the file. What's it's path?

**Comment by onpon4** [comment]
What exactly to run depends on what you have. That command would be the right thing to do *if* you have `naikari-0.9.0.AppImage` in your current working directory. On the other hand, if you installed the game from AUR, you'd do this instead:

```sh
LIBGL_ALWAYS_SOFTWARE=true naikari
```

Since the AUR package installs a `naikari` binary to `/usr/bin`.

**Comment by CreamChatilly** [comment]
is `LIBGL_ALWAYS_SOFTWARE=true naikari` supposed to run the game. Because it failed 💀

**Comment by onpon4** [comment]
It is if you installed the AUR package and have a `naikari` binary in `/usr/bin` (or somewhere else in PATH).

Can I clarify what method you used to download or install Naikari?

🦇

**Comment by onpon4** [comment]
OK, and when you tried `LIBGL_ALWAYS_SOFTWARE=true naikari`, you got the "unable to create OpenGL context" error? If that's the error you got, then that I believe that means that running the game in software mode can't solve the problem unfortunately. On the other hand, if you meant that you got something about "path not found" or similar, I could be mistaken on the command you'd need to run to attempt software mode.

🦇

**Comment by CreamChatilly** [comment]
Yeah sorry if I was unclear. I got the unable to create OpenGL context.

**Comment by onpon4** [comment]
Alright, thanks for clarifying. Sorry it isn't able to run on your hardware. I hope someday you're able to, whether that's by getting new hardware or by someone offering to add OpenGL 2.1 support.

🦇

**Comment by CreamChatilly** [comment]
Thanks for your time. 🙇 
I actually have a second laptop, barely better than my Linux one. I'm gonna try on it later today.
